### ISSUE TITLE
Do you mind some small contribution?

### ISSUE THREAD

**Issue by mamarilmanson** [liammuir/3D_fps_game#1]
I really don't know how to git pull request (will start studying tomorrow)... so just stating things now...

I did some changes to the main game if you don't mind... as a practice for learning godot...

changed to resolution to small to fit my monitor (temp)
gravity -50 -> -60
life and bullets UI margin
top progressbar margin
added green monitor border when getting health pack

![image](https://user-images.githubusercontent.com/3820189/98444939-b5bb0e00-214f-11eb-9531-6f145296bb42.png)
![image](https://user-images.githubusercontent.com/3820189/98444967-e8650680-214f-11eb-9fd4-2af601fc4652.png)

**Comment by liammuir** [comment]
Thank you for submitting the pull request! I have no problem with you modifying the game for learning purposes. This engine is truly amazing, and I hope you continue to learn more about it in the future!

**Comment by mamarilmanson** [comment]
I'll do some pull request sometime then...

**Comment by liammuir** [comment]
Ok! Sounds good.

**Comment by mamarilmanson** [comment]
I apologize in advance... I made some big changes to the code... :worried:
